### PR TITLE
feat: huff-rs wasm bindings

### PR DESCRIPTION
**Pull request by Maddiaa0**
# Overview

This PR extends @Saw-mon-and-Natalie's PR https://github.com/comitylabs/evm.codes/pull/150 from a long time ago to add canonical wasm bindings for huff-rs.

### CODE REVIEW

**Comment by dorlevi** [comment]
I'm sorry for the delay. We were caught up with some of our day job :) we will look into this this week.

**Comment by thevaizman** [comment]
Thanks for contributing @cheethas! Just checking - is this still a draft PR or is it ready for review? :)

**Comment by cheethas** [comment]
Apologies it is still a draft for now, the last thing to do is getting wasm to bundle with the client. I'm afk for the next two weeks but can pick it up then.

**Review by eugenioclrc — APPROVED** [review]

**Comment by peroket** [comment]
Given the lack of update I will close this PR, but feel free to open it again once it's ready to be merged :-)

**Pull request closed without merging**
